name: fgen
description: FGen revolutionizes the way you kickstart your projects, offering a comprehensive suite of tools designed to streamline code generation and project setup. With FGen by your side, starting new projects and adding functionalities becomes a breeze, allowing you to focus on what truly matters—bringing your ideas to life.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
